---
title: "Loading and Manipulating Data in R"
output: 
  html_document:
    theme: readable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
ev <- TRUE
```

# Setup

Install the required package by
```{r eval=FALSE}
install.packages(acs, dependencies = TRUE)
```

Load into the namespace:
```{r message=FALSE, warning=FALSE}
library(acs)
```

Obtain Census API key from [here](http://api.census.gov/data/key_signup.html). Install the key on your system for all future sessions:

```{r eval=FALSE}
api.key.install("1596fcec45b7994ead5cd5d62a6542131df257f6")
```

# Loading Data

* Lookup geography and ACS table:

    ```{r eval=ev}
geo.lookup(state="WA", county="King", county.subdivision = "Seattle")
geo.lookup(state="WA", county="Ki")
```

* Create a geography:

    ```{r eval=ev}
kitsap <- geo.make(state=53, county=35, tract="*", check = TRUE)
```

* Lookup ASC table:

    ```{r eval=ev}
acs.lookup(2015, table.name="Total Population", case.sensitive = FALSE)
```

* Loading data:

    ```{r eval=ev}
popkits <- acs.fetch(endyear = 2015, geography = kitsap, table.number = "B25008") 
head(popkits)
dim(popkits)
acs.colnames(popkits) <- c("Total", "Owner", "Renter")
head(popkits)
```

* Sum and Transformations:

    ```{r eval=ev}
sum(popkits)
ratio <- divide.acs(popkits[,'Renter'], popkits[,'Owner'])
head(ratio)
acs.colnames(ratio) <- 'ratio'
```

* Visualization:

    ```{r eval=ev}
plot(ratio)
plot(popkits[1,])
plot(popkits[1,1])
```

